### ISSUE TITLE
connectAll => hub.connect() never runs

### ISSUE THREAD

**Issue by bsampica** [sketch7/signalr-client#16]
```
 connectAll() {
		// tslint:disable-next-line:forin
		for (const hubKey in this.hubConnections) {
			const hub = this.hubConnections[hubKey];
			hub.connect();
		}
	}
```

You can fix it by subscribing to the hub.connect() observable to make it a hot observable.

 ```
connectAll() {
		// tslint:disable-next-line:forin
		for (const hubKey in this.hubConnections) {
			const hub = this.hubConnections[hubKey];
			hub.connect().subscribe();
		}
	}
```

disconnectAll probably has the same issue, it may be worth it to actually return a subscription from that method as an Map<Observable> or something, so they can be subscribed to individually.

**Comment by bsampica** [comment]
As a side note - implemented in an angular project like this:

`import { HubConnection, HubConnectionOptions, HubConnectionFactory, ConnectionOptions, ConnectionState } from "../signalr-client";
import { Dictionary } from "../signalr-client/utils/dictionary";
import { ConfigurationService } from "./configuration.service";


export class SignalRService {
    private hubConnectionFactory: HubConnectionFactory;

    constructor() {
        console.log('Setting up SignalR Service');
        
        const token = localStorage.getItem('auth_token');
        const connectionString = `${ConfigurationService.baseUrl}/signalr/livevalues?token=${token}`;
        this.hubConnectionFactory = new HubConnectionFactory();
        this.addHub('LiveValuesHub', connectionString);
        this.hubConnectionFactory.connectAll();
        // var http = new HttpConnection(connectionString);
        // var hub = new HubConnection(http);
        // hub.start().then(() => {
        //     console.log('Hub Started');
        // });
    }

    connectAll() {
        this.hubConnectionFactory.connectAll();
    }

    getHub(hubKey: string): HubConnection<{}> {
        return this.hubConnectionFactory.get(hubKey);
    }

    addHub(hubKey, hubUri, data?: Dictionary<string>) {
        this.hubConnectionFactory.create({
            key: hubKey,
            endpointUri: hubUri,
            data: data,
            options: {
                retry: {
                    maximumAttempts: 100,
                    backOffStrategy: {
                        delayRetriesMs: 1000,
                        maxDelayRetriesMs: 10000
                    }
                }
            }
        });
        // options: {
        // retry: {
        //     maximumAttempts: 100,
        //     backOffStrategy: {
        //         delayRetriesMs: 1000,
        //         maxDelayRetriesMs: 10000
        //     }
        // ,
        // randomStrategy: {
        //     min: 0,
        //     max: 0,
        //     intervalMs: 0
        // },
        // randomBackOffStrategy: {
        //     min: 0,
        //     max: 0,
        //     intervalMs: 0,
        // }
        // }
        // },
        // });
        var hub = this.hubConnectionFactory.get(hubKey);
        hub.connectionState$.subscribe((connectionState: ConnectionState) => {
            console.log(`ConnectionState For ${hubKey}`, connectionState);
        })
    }
}`

The token = the JWT auth token I'm using, and there's middleware on the server to look for the token there and authorize the user to the hub.

This is paired with an asp.net core app using the server side library using version 1.0.0-preview1-final

Everything connects with the above modifications, great library!

**Comment by claylaut** [comment]
@bsampica, Thanks for the positive comment 👍  please star my library :)
Regarding issue #1:
Yes, you're right. I will go through them and fix them.

issue #2:
you can achieve this by doing:
- Passing the token to the connect
`this.hubConnection.connect({ token: "my-token"});`
- Or you can use `setData` (this will keep the current state of the connection)
`this.hubConnection.setData({ token: "my token" });`

Hope this helps

**Comment by bsampica** [comment]
Hey @claylaut - thanks for the feedback. 

Can you provide an example of how to call the on function?

**Comment by claylaut** [comment]
You can use the `on` method like this:
```
this.onSend$$ = this.hubConnection.on<string>("Send")
                         .subscribe(val => {
			          console.log(` send :: data received >>>`, val);
		          });
```
