### ISSUE TITLE
[Feature] Allow user to pass the auth token

### ISSUE THREAD

**Issue by sharok** [sketch7/signalr-client#24]
The SignalR supports ASP.NET Core authentication middleware. As I understand you have to pass token via query string. Right now, the only solution is add token when you creates hub with factory:
```
constructor(factory: HubConnectionFactory) {
   factory.create(
      { key: "hero", endpointUri: "/hero?access_token=some_token" }
   );
}
```

The problem is that creating hubs mostly happen in Core/App Modules and in that point you probably has not have token yet.

I think there should be some option that user can use to pass `Observable | string` and the library should add the token. The query string parameter name should be configurable as well, `access_token` by default.  The native signalr library has some `accessTokenFactory ` so maybe you can reuse it.
Some [info](https://github.com/aspnet/SignalR/issues/2425)
This issue is about JWT auth, but I believe SignalR supports cookies as well.

Thanks.

**Comment by claylaut** [comment]
Hi @sharok,
You shouldnt set the token while creating the `HubConnectionFactory`. This should be done at a later stage.

There are two correct usages to pass a token to a connection:
**Connect** 
* Connect accepts a function which it will be called every time that the connection will br connecting
* If connect happens too early and you need to set the auth token later you can use `setData`
https://github.com/sketch7/signalr-client/blob/master/docs/API.md#connect

**SetData**
* SetData allows you to set any connection data at any time, this will keep your connectionstate which means if you where connected, it will automatically reconnect with new options.  
https://github.com/sketch7/signalr-client/blob/master/docs/API.md#setdata

hope this helps.

if you have any concerns please let me know

**Comment by sharok** [comment]
@claylaut my bad, forgot about `setData`. Thanks.
