### ISSUE TITLE
production build failing

### ISSUE THREAD

**Issue by alecrt** [sketch7/signalr-client#30]
Hi, 

i have the following error running ng build --prod using your library.

We followed your angular recipes for integrating the library inside our project:
1. Registered HubConnectionFactory as a Provider
2. Created the named hubs in the module constructor
3. Get the hub from service injected HubConnectionFactory 

Thats the error at the end of the build:

> ERROR in ./src/app/signalr.service.ts
Module not found: Error: Can't resolve '@ssv/signalr-client/hub-connection.factory' in 'D:\Lavori\Macrolux\MacroluxB2B-VNext\ClientApp\src\app'
ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve '@ssv/signalr-client/hub-connection.factory' in 'D:\Lavori\Macrolux\MacroluxB2B-VNext\ClientApp\src\app'

**Comment by alecrt** [comment]
Forget about packages version:
dep:
"@angular/core": "7.2.2"
...
"@ssv/signalr-client": "^1.0.0",

devDep:
"@angular-devkit/build-angular": "^0.12.3",
    "@angular/cli": "^7.2.3",
    "@angular/compiler-cli": "7.2.2",

**Comment by claylaut** [comment]
@alecrt , Sorry for the late reply but I was aboard with limited internet connection.
This is a bug I will fix it straight away, sorry for any inconvenience this may cause.

**Comment by alecrt** [comment]
Thank you, @claylaut! Great work!

**Comment by claylaut** [comment]
@alecrt Thanks, I've updated the build and released a new version `1.0.1`

Please let me know if you have any issues.

**Comment by claylaut** [comment]
@alecrt did you manage to work or you still have any issues?

**Comment by alecrt** [comment]
Compiling without problems now.
Thank you, A.
