### ISSUE TITLE
configure logging level

### ISSUE THREAD

**Issue by alecrt** [sketch7/signalr-client#31]
Is it possible to add a property to configure the signalR logging level using API method configureLogging(signalR.LogLevel.Information) ?

Thank you,
Alessandro

**Comment by claylaut** [comment]
@alecrt, this already exists:
You need to setup this while creating the `HubFactory` as below example:
```
this.hubFactory.create(
	{
		key: "hero",
		endpointUri: "/hero",
		options: {
			logger: LogLevel.Information
		}
	}
);
```

Hope this helps :)
let me know if you have more issues.
