### ISSUE TITLE
serverTimeoutInMilliseconds and keepAliveIntervalInMilliseconds for HubConnection

### ISSUE THREAD

**Issue by vaportrail22** [sketch7/signalr-client#51]
Hi! 
Are there any possibility's to set  serverTimeoutInMilliseconds and keepAliveIntervalInMilliseconds to the HubConnection instance?

**Comment by stephenlautier** [comment]
Unfortunately, currently, it seems not. Since for some reason they didn't expose it as option on the hub, otherwise it would work of the box. 🙁 

When we will add a new release we will consider giving access to the hub so such thing would be still configurable

**Comment by stephenlautier** [comment]
This was added in 3.1.0

e.g.

```ts
this.hubFactory.create({
  key: connectionKey,
  endpointUri: `${environment.apiRemoteBaseUrl}/real-time/hero`,
  configureSignalRHubConnection: hubConnection => { // <--
    hubConnection.keepAliveIntervalInMilliseconds
  }
}
);
```
